SELECT TOP 10 DOC_SAI.HANDLE,
	DOC_SAI.DATAEMISSAO,
	DOC_ENT.*
FROM BB_VENDASDOCUMENTOS ENT
	INNER JOIN FN_DOCUMENTOS DOC_ENT ON DOC_ENT.Handle = ENT.DOCUMENTO
	INNER JOIN FN_LANCAMENTOS LAN_ENT ON LAN_ENT.DOCUMENTO = ENT.DOCUMENTO AND LAN_ENT.ORIGEM = 2 AND LAN_ENT.TIPO = 2
	INNER JOIN FN_CONTAS CON_ENT ON LAN_ENT.CONTA = CON_ENT.Handle AND CON_ENT.Nome LIKE '%COMI%' AND CON_ENT.HANDLE NOT IN (2236, 2284, 2295, 2691)
	INNER JOIN BB_VENDASDOCUMENTOS SAI ON ENT.ACCOUNTING = SAI.ACCOUNTING AND ENT.PESSOA = SAI.PESSOA AND SAI.ENTRADASAIDA = 'S'
	INNER JOIN FN_DOCUMENTOS DOC_SAI ON DOC_SAI.Handle = SAI.DOCUMENTO AND DOC_SAI.EMABERTO='S' AND DOC_SAI.DATACANCELAMENTO IS NULL
	INNER JOIN FN_LANCAMENTOS LAN_SAI ON LAN_SAI.DOCUMENTO = SAI.DOCUMENTO AND LAN_SAI.ORIGEM = 1 AND LAN_SAI.TIPO = 1
	INNER JOIN FN_CONTAS CON_SAI ON LAN_SAI.CONTA = CON_SAI.Handle AND CON_SAI.Nome LIKE '%COMI%' AND CON_SAI.HANDLE NOT IN (2236, 2284, 2295, 2691) AND CON_ENT.HANDLE = CON_SAI.HANDLE
	INNER JOIN BB_PNRACCOUNTINGS A_ENT ON ENT.ACCOUNTING = A_ENT.HANDLE
	INNER JOIN BB_PNRS PNR_ENT ON A_ENT.RLOC = PNR_ENT.HANDLE
WHERE  ENT.ENTRADASAIDA = 'E'
	AND DOC_SAI.DOCUMENTOCONTABIL IN ('3BS5C2-1725969/218484')
ORDER BY DOC_SAI.Handle
