SELECT TOP 10 * FROM BB_PNRACCOUNTINGS WHERE VIAJANTE IS NOT NULL;
SELECT TOP 10 * FROM GN_PESSOAS WHERE EHVIAJANTE = 'S';
SELECT TOP 10 * FROM BB_VIAGENS;
SELECT TOP 10 * FROM BB_VIAGEMACCOUNTINGS;
SELECT TOP 10 * FROM BB_TIPOSDESPESA;
SELECT TOP 10 * FROM BB_VIAGEMDESPESAS;