--						PRIMEIRA ENTRADA ABRE A VIAGEM
--						COM A VIAGEM AINDA FECHADA:
--							PRODUTO = SEGURO -> VIAGEM É A ABRANGENCIA DO SEGURO -> DURAÇÃO DA VIAGEM -> DATA INICIO -> DATA CHEGADA
--							PRODUTO = AÉREO -> CONFIRMAR SE É A PRIMEIRA VIAGEM OU A ÚLTIMA E PEGAR OS TRECHOS COMO COLEÇÃO DE STRING PARA COMPARAR -> PRIMEIRO O ULTIMO VIAGEM, PEGAR AS DATAS LIMITE DA VIAGEM E SOBREPOR AO SEGURO -> RECALCULAR AS DIARIAS
--							PRODUTO = HOTEL -> SE NÃO TEM AEREO E NEM SEGURO PEGAR AS DIARIAS E AS DATAS DE INICIO E FIM DA VIAGEM E COMPARAR COM OS TRECHOS PARA DEFINIR O PRIMEIRO DESTINO
--							
--	VIAGEM ─────────────────────────────────────┐	DATA DE INICIO DA VIAGEM - Ainda não tem viagem, ou mudaram os trechos, ou foi feito o último trecho, ou apareceu outro seguro, ou apareceu um hotel fora da rota
--	│┌─ SEGURO						─┐			│	Abre viagem - Data Origem - Diarias - HaSeguro
--	││┌─ VOO IDA					 │			│	Trechos - Trecho coincide com o inicio dos trechos
--	│││  └─ TRECHOS [FOR-CGH-MIA]	 │			│	Abre viagem - Data Origem - HaAereo = PRECISSA DOS TRECHOS OU DE SEGURO OU DE HOTEL PARA SER LOCALIZADO
--	│││┌─ HOTEL [MIA]				 │ DIARIAS	│	Abre viagem - Data Origem - Data Destino - Diarias - HaHotel
--	││││  -> PASSEIOS				 │ EM MIA	│
--	││││  -> INGRESSOS				 │			│
--	││││  -> CARRO, ETC...			 │			│
--	│││└─							─┘			│
--	│││					LOOP MULTIPLES DESTINOS	│
--	││├─ DESLOCAMENTO				─┐			│	Tem um hotel na cidade do trecho ou a diferência com o voo anterior é superior a 6 horas
--	│││  └─ TRECHOS [MIA-ORL]		 │			│	Data Destino - Diarias - Fecha destino - Abre destino novo - Data Origem - HaAereo = PRECISSA DOS TRECHOS OU DE SEGURO OU DE HOTEL PARA SER LOCALIZADO
--	│││┌─ HOTEL [ORL]				 │ DIARIAS	│	Abre destino novo - Data Origem - Data Destino - Diarias - HaHotel
--	││││  -> PASSEIOS				 │ EM ORL	│
--	││││  -> INGRESSOS				 │			│
--	││││  -> CARRO, ETC...			 │			│
--	│││└─							 │			│
--	│││			FIM DO LOOP MULTIPLES DESTINOS	│
--	││└─ VOO RETORNO				 │			│	Trecho coincide com o final dos trechos
--	││   └─ TRECHOS [ORL-MEX-REC]	 │			│	Data Destino - Fecha destino - Diarias = PRECISSA DOS TRECHOS OU DE SEGURO OU DE HOTEL PARA SER LOCALIZADO
--	│└─								─┘			│
--	└───────────────────────────────────────────┘	DATA DE FIM DA VIAGEM


DECLARE @USUARIO AS INT
SET @USUARIO = 1276

DECLARE @DATAINICIO AS DATE
SET @DATAINICIO = '01/09/2017'

DECLARE @DATAFINAL AS DATE
SET @DATAFINAL = '18/09/2017'

DECLARE @SITUACOES TABLE(HANDLE int, SITUACAO varchar(15))
INSERT INTO @SITUACOES (HANDLE, SITUACAO) values (1, 'Ativo'), (2, 'Cancelado')

DECLARE @PRODUTOS TABLE(HANDLE int, PRODUTO varchar(15), PESO int)
INSERT INTO @PRODUTOS (HANDLE, PRODUTO, PESO) values 
	(1, 'Aéreo', 2),
	(2, 'Hotel', 3),
	(3, 'Carro', 4),
	(4, 'Miscelaneo', 1),
	(5, 'Aéreo', 2),
	(6, 'Aéreo', 2),
	(7, 'Aéreo', 2),
	(8, 'Rodoviário', 2)

DECLARE @TIPOSEMISSAO TABLE(HANDLE varchar(1), TIPOEMISSAO varchar(15))
INSERT INTO @TIPOSEMISSAO (HANDLE, TIPOEMISSAO) values ('A', 'Ativo'), ('E', 'Externa'), ('M', 'Manual')

DECLARE @TIPOSVOO TABLE(HANDLE varchar(1), TIPOVOO varchar(15))
INSERT INTO @TIPOSVOO (HANDLE, TIPOVOO) values ('D', 'Doméstico'), ('F', 'Internacional'), ('T', 'Regional')

DECLARE @FORMASPAGAMENTO TABLE(HANDLE int, FORMAPAGAMENTO varchar(20))
INSERT INTO @FORMASPAGAMENTO (HANDLE, FORMAPAGAMENTO) values 
	(1, 'Cartão'),
	(2, 'Invoice'),
	(3, 'Outras'),
	(4, 'GR'),
	(5, 'Múltiplos pagamentos')

DECLARE @FORMASRECEBIMENTO TABLE(HANDLE int, FORMARECEBIMENTO varchar(30))
INSERT INTO @FORMASRECEBIMENTO (HANDLE, FORMARECEBIMENTO) values 
	(1, 'Cash'),
	(3, 'Faturado'),
	(5, 'Cheque'),
	(6, 'Pagamento direto'),
	(7, 'Cartão'),
	(9, 'Cartão convênio'),
	(10, 'Sem adicional'),
	(11, 'Cartão AMEX'),
	(12, 'Governo'),
	(13, 'Cheque pré-datado'),
	(14, 'As financiadas por terceiros'),
	(15, 'Múltiplos recebimentos'),
	(16, 'Despesas internas'),
	(17, 'TKT'),
	(18, 'MCO')

SELECT
	A.HANDLE,
	SIT.SITUACAO,
	PNR.REEMISSAO,
	CONVERT(DATE, A.DATAEMISSAO) AS DATAEMISSAO,
	A.AGENTE_EMISSAO AS EMISSOR_ID,
	AGE.NOME AS EMISSOR_NOME,
	PNR.BB_RLOC AS RLOC,
	PNR.LOCALIZADORACIA AS LOC,
	A.INFAPROVADOR AS APROVADOR,
	CASE A.PRODUTO WHEN 4 THEN TIPMIS.NOME ELSE PRO.PRODUTO END AS PRODUTO,
	ISNULL(CONS.NOME, '') AS CONSOLIDADORA,
	CONVERT(VARCHAR(50), FORN.NOME) AS FORNECEDOR,
	ISNULL(A.BILHETE, '') AS BILHETE,
	ISNULL(A.CONFIRMACAO, '') AS CONFIRMACAO,
	ISNULL(TEMI.TIPOEMISSAO, '') AS TIPODEEMISSAO,
	CONVERT(VARCHAR(50), CLI.NOME) AS CLIENTE,
	ISNULL(TVOO.TIPOVOO, '')  AS TIPOVOO,
	ISNULL(A.PASSAGEIRONAOCAD, '') AS PASSAGEIRO,
	ISNULL(PASS.NOME, 'Não cadastrado') AS NOME_COMPLETO,
	ISNULL(PASS.CPF, 'Não cadastrado') AS CPF,
	ISNULL(A.TRECHOS, '') AS TRECHOS,
	CONVERT(DATETIME, ISNULL(TRE.BB_AEREO_DATA_VOO, ISNULL(A.BB_MISC_ENTRADA, ISNULL(A.BB_CARRO_RETIRADA, A.BB_HOTEL_ENTRADA))) + ' ' + ISNULL(TRE.BB_AEREO_HRSAIDA, '00:00:00')) AS DATA_ORIGEM,
	ISNULL(TRE.BB_AEREO_ORIGEM, '') AS AEREO_ORIGEM,
	ISNULL(ORI_MUN.NOME, '') AS MUNICIPIO_ORIGEM,
	ISNULL(CASE ORI_PAIS.NOME WHEN 'Brasil' THEN ORI_EST.NOME ELSE NULL END, '') AS ESTADO_ORIGEM,
	ISNULL(CASE ORI_PAIS.NOME WHEN 'Brasil' THEN ORI_REG.NOME ELSE NULL END, '') AS REGIAO_ORIGEM,
	ISNULL(ORI_PAIS.NOME, '') AS PAIS_ORIGEM,
	ISNULL(CASE ORI_PAIS.NOME WHEN 'Brasil' THEN 'América Do Sul' ELSE ORI_REG.NOME END, '') AS CONTINENTE_ORIGEM,
	CONVERT(DATETIME, ISNULL((CASE WHEN CONVERT(DATETIME, TRE.BB_AEREO_DATA_VOO + TRE.BB_AEREO_HRSAIDA) > CONVERT(DATETIME, TRE.BB_AEREO_DATA_VOO + TRE.BB_AEREO_HRCHEGADA) THEN DATEADD(DAY, 1, TRE.BB_AEREO_DATA_VOO) ELSE TRE.BB_AEREO_DATA_VOO END), ISNULL(A.BB_MISC_SAIDA, ISNULL(A.BB_CARRO_ENTREGA, A.BB_HOTEL_SAIDA))) + ' ' + ISNULL(TRE.BB_AEREO_HRSAIDA, '')) AS DATA_DESTINO,
	ISNULL(ISNULL(TRE.BB_AEREO_DESTINO, DES_MUN.SIGLA), '') AS AEREO_DESTINO,
	ISNULL(DES_MUN.NOME, '') AS MUNICIPIO_DESTINO,
	ISNULL(CASE DES_PAIS.NOME WHEN 'Brasil' THEN DES_EST.NOME ELSE NULL END, '') AS ESTADO_DESTINO,
	ISNULL(CASE DES_PAIS.NOME WHEN 'Brasil' THEN DES_REG.NOME ELSE NULL END, '') AS REGIAO_DESTINO,
	ISNULL(DES_PAIS.NOME, '') AS PAIS_DESTINO,
	ISNULL(CASE DES_PAIS.NOME WHEN 'Brasil' THEN 'América Do Sul' ELSE DES_REG.NOME END, '') AS CONTINENTE_DESTINO,
	FPAG.FORMAPAGAMENTO AS FORMADEPAGAMENTO,
	FREC.FORMARECEBIMENTO AS FORMARECEBIMENTO,
	PCCAGE.PCC AS PCC_EMISSAO,
	CC.NOME AS CC_CASABLANCA,
	CLI_CC.CENTROCUSTO AS CC_CLIENTE
FROM BB_PNRACCOUNTINGS A
	INNER JOIN BB_PNRS PNR ON PNR.HANDLE = A.RLOC
	INNER JOIN GN_PESSOAS CLI ON CLI.HANDLE = A.BB_CLIENTE
	LEFT JOIN BB_CLIENTECC AS CLI_CC ON A.CENTRODECUSTO = CLI_CC.HANDLE
	LEFT OUTER JOIN GN_GRUPOSEMPRESARIAIS GP ON GP.HANDLE = CLI.GRUPOEMPRESARIAL
	LEFT OUTER JOIN GN_PESSOAS GPP ON GPP.HANDLE = GP.PESSOA
	INNER JOIN GN_PESSOAS FORN ON FORN.HANDLE = A.FORNECEDOR
	LEFT JOIN GN_PESSOAS AS CONS ON A.CONSOLIDADOR = CONS.HANDLE
	LEFT JOIN @SITUACOES AS SIT ON SIT.HANDLE = A.SITUACAO
	LEFT JOIN BB_AGENTES AS AGE ON A.AGENTE_EMISSAO = AGE.HANDLE
	LEFT JOIN @PRODUTOS AS PRO ON PRO.HANDLE = A.PRODUTO
	LEFT JOIN BB_TIPOMISCELANIO AS TIPMIS ON A.TIPOMISCELANIO = TIPMIS.HANDLE
	LEFT JOIN @TIPOSEMISSAO AS TEMI ON TEMI.HANDLE = A.TIPODEEMISSAO
	LEFT JOIN @TIPOSVOO AS TVOO ON TVOO.HANDLE = A.TIPOVOO
	LEFT JOIN GN_PESSOACONTATOS PASS ON PASS.PESSOA = CLI.HANDLE AND PASS.NOME LIKE REPLACE(CASE WHEN 
		CHARINDEX('/', A.PASSAGEIRONAOCAD) = 0 
		THEN A.PASSAGEIRONAOCAD ELSE 
		RIGHT(A.PASSAGEIRONAOCAD, LEN(A.PASSAGEIRONAOCAD) - CHARINDEX('/', A.PASSAGEIRONAOCAD))
		+ ' ' + 
		LEFT(A.PASSAGEIRONAOCAD, CHARINDEX('/', A.PASSAGEIRONAOCAD) - 1)
		END, ' ', '%')
--	LEFT JOIN BB_PNRPASSAGEIROS AS PASS ON A.PASSAGEIROCAD = PASS.HANDLE
	LEFT JOIN BB_TRECHOACCOUNTING TRE_A ON A.HANDLE = TRE_A.ACCOUNTING
	LEFT JOIN BB_PNRTRECHOS AS TRE ON TRE.HANDLE = TRE_A.TRECHO
	LEFT JOIN BB_AEROPORTOS AS DES_AERO ON DES_AERO.AEROPORTO = TRE.BB_AEREO_DESTINO
	LEFT JOIN MUNICIPIOS AS DES_MUN ON (PRO.PRODUTO = 'Aéreo' AND DES_MUN.HANDLE = DES_AERO.CIDADE) OR (PRO.PRODUTO <> 'Aéreo' AND DES_MUN.HANDLE = FORN.MUNICIPIO)
	LEFT JOIN ESTADOS DES_EST ON DES_EST.HANDLE = DES_MUN.ESTADO
	LEFT JOIN PAISES DES_PAIS ON DES_PAIS.HANDLE = DES_MUN.PAIS
	LEFT JOIN K_REGIOES DES_REG ON DES_REG.HANDLE = DES_PAIS.K_CONTINENTE OR DES_REG.HANDLE = DES_EST.K_REGIAO
	LEFT JOIN BB_AEROPORTOS AS ORI_AERO ON ORI_AERO.AEROPORTO = TRE.BB_AEREO_ORIGEM
	LEFT JOIN MUNICIPIOS AS ORI_MUN ON ORI_MUN.HANDLE = ORI_AERO.CIDADE
	LEFT JOIN ESTADOS ORI_EST ON ORI_EST.HANDLE = ORI_MUN.ESTADO
	LEFT JOIN PAISES ORI_PAIS ON ORI_PAIS.HANDLE = ORI_MUN.PAIS
	LEFT JOIN K_REGIOES ORI_REG ON ORI_REG.HANDLE = ORI_PAIS.K_CONTINENTE OR ORI_REG.HANDLE = ORI_EST.K_REGIAO
	LEFT JOIN @FORMASPAGAMENTO AS FPAG ON FPAG.HANDLE = A.FORMADEPAGAMENTO
	LEFT JOIN @FORMASRECEBIMENTO AS FREC ON FREC.HANDLE = A.FORMARECEBIMENTO
	LEFT JOIN BB_MAQUINAS AS PCCAGE ON A.PCC_EMISSAO = PCCAGE.HANDLE
	LEFT JOIN BB_CCPROJETOACC AS CCPROJ ON A.HANDLE = CCPROJ.ACCOUNTING
	LEFT JOIN CT_CC AS CC ON CCPROJ.CCSUGERIDO = CC.HANDLE
WHERE CONVERT(DATETIME, ISNULL(TRE.BB_AEREO_DATA_VOO, ISNULL(A.BB_MISC_ENTRADA, ISNULL(A.BB_CARRO_RETIRADA, A.BB_HOTEL_ENTRADA))) + ' ' + ISNULL(TRE.BB_AEREO_HRSAIDA, '00:00:00')) <= @DATAFINAL
	AND CONVERT(DATETIME, ISNULL((CASE WHEN CONVERT(DATETIME, TRE.BB_AEREO_DATA_VOO + TRE.BB_AEREO_HRSAIDA) > CONVERT(DATETIME, TRE.BB_AEREO_DATA_VOO + TRE.BB_AEREO_HRCHEGADA) THEN DATEADD(DAY, 1, TRE.BB_AEREO_DATA_VOO) ELSE TRE.BB_AEREO_DATA_VOO END), ISNULL(A.BB_MISC_SAIDA, ISNULL(A.BB_CARRO_ENTREGA, A.BB_HOTEL_SAIDA))) + ' ' + ISNULL(TRE.BB_AEREO_HRSAIDA, '')) >= @DATAINICIO
	AND ((A.BB_CLIENTE IN (
		SELECT PES.HANDLE
		FROM GN_PESSOAS PES
		WHERE PES.GRUPOEMPRESARIAL IN (
			SELECT PESSOA
			FROM BB_USUARIOPESSOAS
			WHERE USUARIO = @USUARIO
			AND GRUPOEMPRESARIAL = 'S'))
		OR A.BB_CLIENTE IN (
			SELECT PESSOA
			FROM BB_USUARIOPESSOAS
			WHERE USUARIO = @USUARIO)))
	AND A.SITUACAO = 1
	AND PNR.REEMISSAO = 'N'
ORDER BY CC_CLIENTE, PASSAGEIRO, CONVERT(DATE, ISNULL(TRE.BB_AEREO_DATA_VOO, ISNULL(A.BB_MISC_ENTRADA, ISNULL(A.BB_CARRO_RETIRADA, A.BB_HOTEL_ENTRADA)))), CASE WHEN A.PRODUTO <> 4 OR TIPMIS.HANDLE = 1 THEN PESO ELSE 5 END, RLOC
