--	senha: vta1802

DECLARE @FATURA AS INT
SET @FATURA = 168826

SELECT 
	ACC.DATAEMISSAO, 
	FD.BB_RLOC NUMERORESERVA, 
	ACC.HANDLE CODIGORESERVA, 
	ACC.INFOS, 
	ACC.INFMOTIVO, 
	PNR.OBSERVACAO AS OBSERVACOES,
	PES.NOME FORNECEDOR, 
	ACC.PRODUTO PRODUTO,  
	ACC.PASSAGEIRONAOCAD PASSAGEIRO, 
	ACC.TRECHOS TRECHO, 
	NULL CIDADE, 
	CC.CENTROCUSTO CENTROCUSTO, 
	ACC.PROJETO PROJETO,  
	(SELECT TOP 1 A1.BB_AEREO_DATA_VOO   
		FROM BB_PNRTRECHOS A1   
		INNER JOIN BB_TRECHOACCOUNTING A2 ON (A2.ACCOUNTING = ACC.HANDLE AND A2.TRECHO = A1.HANDLE)
		ORDER BY A1.BB_AEREO_DATA_VOO) DATAVIAGEMAEREO,  
	(SELECT TOP 1 A1.BB_AEREO_DATA_VOO   
		FROM BB_PNRTRECHOS A1   
		INNER JOIN BB_TRECHOACCOUNTING A2 ON (A2.ACCOUNTING = ACC.HANDLE AND A2.TRECHO = A1.HANDLE)   
		ORDER BY A1.BB_AEREO_DATA_VOO DESC) DATARETORNOAEREO,   
	NULL DATAIN, 
	NULL DATAOUT,  
	ACC.BB_CARRO_ENTREGA,
	ACC.QUANTIDADE,
	ROUND((ISNULL(ACC.TARIFA,0) + ISNULL(VD.MARKUP,0)),2) TARIFA, 
	ROUND(ISNULL(VD.TAXA,0),2) TAXAEMBARQUE, 
	0 TAXASERVICO,  
	ROUND(ISNULL(VD.MANAGEMENTFEE,0),2) TAXASERVICOFEE, 
	ROUND(ISNULL(VD.TAXADU,0),2) TAXADU, 
	0 EXTRAS,  
	ROUND((ISNULL(VD.OUTRASTAXASAJUSTADAS,0) + ISNULL(ACC.TAXAADM,0)),2) OUTRASTAXAS, 
	(ROUND(VD.DESCONTOCONCEDIDO,2)) DESCONTO,  
	SOL.NOME SOLICITANTE  
FROM 
	BB_VENDASDOCUMENTOS VD  
	INNER JOIN BB_FATURADOCUMENTOS FD ON (VD.HANDLE = FD.DOCUMENTOVENDA)  
	INNER JOIN BB_FATURAS FAT ON (FAT.HANDLE = FD.FATURA)  
	INNER JOIN BB_PNRACCOUNTINGS ACC ON (ACC.HANDLE = VD.ACCOUNTING)  
	INNER JOIN BB_PNRS PNR ON (ACC.RLOC = PNR.HANDLE) 
	INNER JOIN GN_PESSOAS PES ON (PES.HANDLE = ACC.FORNECEDOR)  
	LEFT JOIN BB_CLIENTECC CC ON (VD.CENTRODECUSTO = CC.HANDLE)  
	LEFT JOIN GN_PESSOACONTATOS SOL ON (SOL.HANDLE = ACC.SOLICITANTE)  
WHERE
	FAT.HANDLE = @FATURA  
	AND FD.DOCUMENTOLANCAMENTO IS NULL  
	AND FD.EMDISPUTA <> 'S' 
	AND FD.RETIRADO <> 'S'  
	AND VD.TIPOACCOUNTING <> 'R'  
	AND ACC.PRODUTO IN (1,5,6,7)  
	AND VD.FORMARECEBIMENTO IN (3, 12)
UNION ALL
SELECT 
	ACC.DATAEMISSAO, 
	FD.BB_RLOC NUMERORESERVA, 
	ACC.HANDLE CODIGORESERVA, 
	ACC.INFOS, ACC.INFMOTIVO, 
	PNR.OBSERVACAO AS OBSERVACOES,
	PES.NOME FORNECEDOR, 
	ACC.PRODUTO PRODUTO,  
	ACC.PASSAGEIRONAOCAD PASSAGEIRO, 
	NULL TRECHO, 
	CIDADE.NOME CIDADE, 
	CC.CENTROCUSTO CENTROCUSTO, 
	ACC.PROJETO PROJETO,  
	NULL DATAVIAGEMAEREO, 
	NULL DATARETORNOAEREO,  
	VD.DATAIN,  
	VD.DATAOUT,  
	ACC.BB_CARRO_ENTREGA,
	ACC.QUANTIDADE,
	ROUND((ISNULL(VD.VALORNOMINALAJUSTADO,0) + ISNULL(VD.MARKUP,0)),2) TARIFA,  
	0 TAXAEMBARQUE,  
	0 TAXASERVICO,  
	ROUND(ISNULL(VD.MANAGEMENTFEE,0),2) TAXASERVICOFEE,  
	0 TAXADU,  
	ROUND(ISNULL(VD.EXTRAS,0),2) EXTRAS,  
	ROUND((ISNULL(VD.TAXAAJUSTADA,0) + ISNULL(VD.OUTRASTAXASAJUSTADAS,0) + ISNULL(VD.ALIMENTACAO,0) + ISNULL(ACC.TAXAADM,0)),2) OUTRASTAXAS,  
	(ROUND(VD.DESCONTOCONCEDIDO,2)) DESCONTO, 
	SOL.NOME SOLICITANTE  
FROM
	BB_VENDASDOCUMENTOS VD  
	LEFT JOIN BB_VENDASDOCADICIONAL AD ON (AD.DOCDEPENDENTE = VD.HANDLE)  
	LEFT JOIN BB_VENDASDOCUMENTOS DOCF ON (DOCF.HANDLE = AD.DOCORIGINAL)  
	INNER JOIN BB_FATURADOCUMENTOS FD ON (VD.HANDLE = FD.DOCUMENTOVENDA)  
	INNER JOIN BB_FATURAS FAT ON (FAT.HANDLE = FD.FATURA)  
	INNER JOIN BB_PNRACCOUNTINGS ACC ON (ACC.HANDLE = VD.ACCOUNTING)  
	INNER JOIN BB_PNRS PNR ON (PNR.HANDLE = ACC.RLOC)  
	INNER JOIN GN_PESSOAS PES ON (PES.HANDLE = ACC.FORNECEDOR)  
	LEFT JOIN MUNICIPIOS CIDADE ON (CIDADE.HANDLE = PES.MUNICIPIO)  
	LEFT JOIN BB_CLIENTECC CC ON (VD.CENTRODECUSTO = CC.HANDLE)  
	LEFT JOIN GN_PESSOACONTATOS SOL ON (SOL.HANDLE = ACC.SOLICITANTE)  
WHERE
	FAT.HANDLE = @FATURA  
	AND FD.DOCUMENTOLANCAMENTO IS NULL  
	AND FD.EMDISPUTA <> 'S' 
	AND FD.RETIRADO <> 'S'  
	AND VD.TIPOACCOUNTING <> 'R'  
	AND ACC.PRODUTO IN (2,3,4,8)
ORDER BY 1, 2





SELECT ACC.DATAEMISSAO, FD.BB_RLOC NUMERORESERVA, ACC.HANDLE CODIGORESERVA, ACC.INFOS, ACC.INFMOTIVO, PNR.OBSERVACAO AS OBSERVACOES, PES.NOME FORNECEDOR, ACC.PRODUTO PRODUTO,  ACC.PASSAGEIRONAOCAD PASSAGEIRO, ACC.TRECHOS TRECHO, NULL CIDADE, CC.CENTROCUSTO CENTROCUSTO, ACC.PROJETO PROJETO,  (SELECT TOP 1 A1.BB_AEREO_DATA_VOO   FROM BB_PNRTRECHOS A1   INNER JOIN BB_TRECHOACCOUNTING A2 ON (A2.ACCOUNTING = ACC.HANDLE AND A2.TRECHO = A1.HANDLE)   ORDER BY A1.BB_AEREO_DATA_VOO) DATAVIAGEMAEREO,  (SELECT TOP 1 A1.BB_AEREO_DATA_VOO   FROM BB_PNRTRECHOS A1   INNER JOIN BB_TRECHOACCOUNTING A2 ON (A2.ACCOUNTING = ACC.HANDLE AND A2.TRECHO = A1.HANDLE)   ORDER BY A1.BB_AEREO_DATA_VOO DESC) DATARETORNOAEREO,   NULL DATAIN, NULL DATAOUT,  ROUND((ISNULL(ACC.TARIFA,0) + ISNULL(VD.MARKUP,0)),2) TARIFA, ROUND(ISNULL(VD.TAXA,0),2) TAXAEMBARQUE, 0 TAXASERVICO,  ROUND(ISNULL(VD.MANAGEMENTFEE,0),2) TAXASERVICOFEE, ROUND(ISNULL(VD.TAXADU,0),2) TAXADU, 0 EXTRAS,  ROUND((ISNULL(VD.OUTRASTAXASAJUSTADAS,0) + ISNULL(ACC.TAXAADM,0)),2) OUTRASTAXAS, (ROUND(VD.DESCONTOCONCEDIDO,2)) DESCONTO,  SOL.NOME SOLICITANTE  FROM BB_VENDASDOCUMENTOS VD  INNER JOIN BB_FATURADOCUMENTOS FD ON (VD.HANDLE = FD.DOCUMENTOVENDA)  INNER JOIN BB_FATURAS FAT ON (FAT.HANDLE = FD.FATURA)  INNER JOIN BB_PNRACCOUNTINGS ACC ON (ACC.HANDLE = VD.ACCOUNTING)  INNER JOIN BB_PNRS PNR ON (ACC.RLOC = PNR.HANDLE)  INNER JOIN GN_PESSOAS PES ON (PES.HANDLE = ACC.FORNECEDOR)  LEFT JOIN BB_CLIENTECC CC ON (VD.CENTRODECUSTO = CC.HANDLE)  LEFT JOIN GN_PESSOACONTATOS SOL ON (SOL.HANDLE = ACC.SOLICITANTE)  WHERE FAT.HANDLE = :PFATURA  AND FD.DOCUMENTOLANCAMENTO IS NULL  AND FD.EMDISPUTA <> 'S' AND FD.RETIRADO <> 'S'  AND VD.TIPOACCOUNTING <> 'R'  AND ACC.PRODUTO IN (1,5,6,7)  AND VD.FORMARECEBIMENTO IN (3, 12)  UNION ALL  SELECT ACC.DATAEMISSAO, FD.BB_RLOC NUMERORESERVA, ACC.HANDLE CODIGORESERVA, ACC.INFOS, ACC.INFMOTIVO, PNR.OBSERVACAO AS OBSERVACOES, PES.NOME FORNECEDOR, ACC.PRODUTO PRODUTO,  ACC.PASSAGEIRONAOCAD PASSAGEIRO, NULL TRECHO, CIDADE.NOME CIDADE, CC.CENTROCUSTO CENTROCUSTO, ACC.PROJETO PROJETO,  NULL DATAVIAGEMAEREO, NULL DATARETORNOAEREO,  VD.DATAIN,  VD.DATAOUT,  ROUND((ISNULL(VD.VALORNOMINALAJUSTADO,0) + ISNULL(VD.MARKUP,0)),2) TARIFA,  0 TAXAEMBARQUE,  0 TAXASERVICO,  ROUND(ISNULL(VD.MANAGEMENTFEE,0),2) TAXASERVICOFEE,  0 TAXADU,  ROUND(ISNULL(VD.EXTRAS,0),2) EXTRAS,  ROUND((ISNULL(VD.TAXAAJUSTADA,0) + ISNULL(VD.OUTRASTAXASAJUSTADAS,0) + ISNULL(VD.ALIMENTACAO,0) + ISNULL(ACC.TAXAADM,0)),2) OUTRASTAXAS,  (ROUND(VD.DESCONTOCONCEDIDO,2)) DESCONTO, SOL.NOME SOLICITANTE  FROM BB_VENDASDOCUMENTOS VD  LEFT JOIN BB_VENDASDOCADICIONAL AD ON (AD.DOCDEPENDENTE = VD.HANDLE)  LEFT JOIN BB_VENDASDOCUMENTOS DOCF ON (DOCF.HANDLE = AD.DOCORIGINAL)  INNER JOIN BB_FATURADOCUMENTOS FD ON (VD.HANDLE = FD.DOCUMENTOVENDA)  INNER JOIN BB_FATURAS FAT ON (FAT.HANDLE = FD.FATURA)  INNER JOIN BB_PNRACCOUNTINGS ACC ON (ACC.HANDLE = VD.ACCOUNTING)  INNER JOIN BB_PNRS PNR ON (PNR.HANDLE = ACC.RLOC)  INNER JOIN GN_PESSOAS PES ON (PES.HANDLE = ACC.FORNECEDOR)  LEFT JOIN MUNICIPIOS CIDADE ON (CIDADE.HANDLE = PES.MUNICIPIO)  LEFT JOIN BB_CLIENTECC CC ON (VD.CENTRODECUSTO = CC.HANDLE)  LEFT JOIN GN_PESSOACONTATOS SOL ON (SOL.HANDLE = ACC.SOLICITANTE)  WHERE FAT.HANDLE = :PFATURA  AND FD.DOCUMENTOLANCAMENTO IS NULL  AND FD.EMDISPUTA <> 'S' AND FD.RETIRADO <> 'S'  AND VD.TIPOACCOUNTING <> 'R'  AND ACC.PRODUTO IN (2,3,4,8)  ORDER BY 1, 2



SELECT ACC.DATAEMISSAO, FD.BB_RLOC NUMERORESERVA, ACC.HANDLE CODIGORESERVA, ACC.INFOS, ACC.INFMOTIVO, PNR.OBSERVACAO AS OBSERVACOES, PES.NOME FORNECEDOR, ACC.PRODUTO PRODUTO,  ACC.PASSAGEIRONAOCAD PASSAGEIRO, ACC.TRECHOS TRECHO, NULL CIDADE, CC.CENTROCUSTO CENTROCUSTO, ACC.PROJETO PROJETO,  (SELECT TOP 1 A1.BB_AEREO_DATA_VOO   FROM BB_PNRTRECHOS A1   INNER JOIN BB_TRECHOACCOUNTING A2 ON (A2.ACCOUNTING = ACC.HANDLE AND A2.TRECHO = A1.HANDLE)   ORDER BY A1.BB_AEREO_DATA_VOO) DATAVIAGEMAEREO,  (SELECT TOP 1 A1.BB_AEREO_DATA_VOO   FROM BB_PNRTRECHOS A1   INNER JOIN BB_TRECHOACCOUNTING A2 ON (A2.ACCOUNTING = ACC.HANDLE AND A2.TRECHO = A1.HANDLE)   ORDER BY A1.BB_AEREO_DATA_VOO DESC) DATARETORNOAEREO,   NULL DATAIN, NULL DATAOUT, ACC.BB_CARRO_ENTREGA, ROUND((ISNULL(ACC.TARIFA,0) + ISNULL(VD.MARKUP,0)),2) TARIFA, ROUND(ISNULL(VD.TAXA,0),2) TAXAEMBARQUE, 0 TAXASERVICO,  ROUND(ISNULL(VD.MANAGEMENTFEE,0),2) TAXASERVICOFEE, ROUND(ISNULL(VD.TAXADU,0),2) TAXADU, 0 EXTRAS,  ROUND((ISNULL(VD.OUTRASTAXASAJUSTADAS,0) + ISNULL(ACC.TAXAADM,0)),2) OUTRASTAXAS, (ROUND(VD.DESCONTOCONCEDIDO,2)) DESCONTO,  SOL.NOME SOLICITANTE  FROM BB_VENDASDOCUMENTOS VD  INNER JOIN BB_FATURADOCUMENTOS FD ON (VD.HANDLE = FD.DOCUMENTOVENDA)  INNER JOIN BB_FATURAS FAT ON (FAT.HANDLE = FD.FATURA)  INNER JOIN BB_PNRACCOUNTINGS ACC ON (ACC.HANDLE = VD.ACCOUNTING)  INNER JOIN BB_PNRS PNR ON (ACC.RLOC = PNR.HANDLE)  INNER JOIN GN_PESSOAS PES ON (PES.HANDLE = ACC.FORNECEDOR)  LEFT JOIN BB_CLIENTECC CC ON (VD.CENTRODECUSTO = CC.HANDLE)  LEFT JOIN GN_PESSOACONTATOS SOL ON (SOL.HANDLE = ACC.SOLICITANTE)  WHERE FAT.HANDLE = :PFATURA  AND FD.DOCUMENTOLANCAMENTO IS NULL  AND FD.EMDISPUTA <> 'S' AND FD.RETIRADO <> 'S'  AND VD.TIPOACCOUNTING <> 'R'  AND ACC.PRODUTO IN (1,5,6,7)  AND VD.FORMARECEBIMENTO IN (3, 12)  UNION ALL  SELECT ACC.DATAEMISSAO, FD.BB_RLOC NUMERORESERVA, ACC.HANDLE CODIGORESERVA, ACC.INFOS, ACC.INFMOTIVO, PNR.OBSERVACAO AS OBSERVACOES, PES.NOME FORNECEDOR, ACC.PRODUTO PRODUTO,  ACC.PASSAGEIRONAOCAD PASSAGEIRO, NULL TRECHO, CIDADE.NOME CIDADE, CC.CENTROCUSTO CENTROCUSTO, ACC.PROJETO PROJETO,  NULL DATAVIAGEMAEREO, NULL DATARETORNOAEREO,  VD.DATAIN,  VD.DATAOUT, ACC.BB_CARRO_ENTREGA, ROUND((ISNULL(VD.VALORNOMINALAJUSTADO,0) + ISNULL(VD.MARKUP,0)),2) TARIFA,  0 TAXAEMBARQUE,  0 TAXASERVICO,  ROUND(ISNULL(VD.MANAGEMENTFEE,0),2) TAXASERVICOFEE,  0 TAXADU,  ROUND(ISNULL(VD.EXTRAS,0),2) EXTRAS,  ROUND((ISNULL(VD.TAXAAJUSTADA,0) + ISNULL(VD.OUTRASTAXASAJUSTADAS,0) + ISNULL(VD.ALIMENTACAO,0) + ISNULL(ACC.TAXAADM,0)),2) OUTRASTAXAS,  (ROUND(VD.DESCONTOCONCEDIDO,2)) DESCONTO, SOL.NOME SOLICITANTE  FROM BB_VENDASDOCUMENTOS VD  LEFT JOIN BB_VENDASDOCADICIONAL AD ON (AD.DOCDEPENDENTE = VD.HANDLE)  LEFT JOIN BB_VENDASDOCUMENTOS DOCF ON (DOCF.HANDLE = AD.DOCORIGINAL)  INNER JOIN BB_FATURADOCUMENTOS FD ON (VD.HANDLE = FD.DOCUMENTOVENDA)  INNER JOIN BB_FATURAS FAT ON (FAT.HANDLE = FD.FATURA)  INNER JOIN BB_PNRACCOUNTINGS ACC ON (ACC.HANDLE = VD.ACCOUNTING)  INNER JOIN BB_PNRS PNR ON (PNR.HANDLE = ACC.RLOC)  INNER JOIN GN_PESSOAS PES ON (PES.HANDLE = ACC.FORNECEDOR)  LEFT JOIN MUNICIPIOS CIDADE ON (CIDADE.HANDLE = PES.MUNICIPIO)  LEFT JOIN BB_CLIENTECC CC ON (VD.CENTRODECUSTO = CC.HANDLE)  LEFT JOIN GN_PESSOACONTATOS SOL ON (SOL.HANDLE = ACC.SOLICITANTE)  WHERE FAT.HANDLE = :PFATURA  AND FD.DOCUMENTOLANCAMENTO IS NULL  AND FD.EMDISPUTA <> 'S' AND FD.RETIRADO <> 'S'  AND VD.TIPOACCOUNTING <> 'R'  AND ACC.PRODUTO IN (2,3,4,8)  ORDER BY 1, 2